// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbCajas
    {
        public int caja_Id { get; set; }
        public int? caja_UsuarioApertura { get; set; }
        public DateTime? caja_FechaApertura { get; set; }
        public int? caja_UsuarioCierre { get; set; }
        public DateTime? caja_FechaCierre { get; set; }
        public decimal? caja_MontoInicial { get; set; }
        public decimal? caja_MontoFinal { get; set; }
        public decimal? caja_MontoSistema { get; set; }
        public int? Sucu_Id { get; set; }
    }
}