// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbEmpleados
    {
        public tbEmpleados()
        {
            tbFactura = new HashSet<tbFactura>();
        }
        [NotMapped]
        public string Empl_DNI { get; set; }
        [NotMapped]
        public string Depa_Codigo { get; set; }
        [NotMapped]
        public string Depa_Departamento { get; set; }
        [NotMapped]
        public string Muni_Municipio { get; set; }
        [NotMapped]
        public string Esta_EstadoCivil { get; set; }
        [NotMapped]
        public string Carg_Cargo { get; set; }
        [NotMapped]
        public string Empl_Correo { get; set; }

        public int Empl_Id { get; set; }
        public string Empl_Nombre { get; set; }
        public string Empl_Apellido { get; set; }
        public string Empl_Sexo { get; set; }
        public DateTime Empl_FechaNac { get; set; }
        public string Muni_Codigo { get; set; }
        public int Esta_Id { get; set; }
        public int Carg_Id { get; set; }
        public int Sucu_Id { get; set; }
        public int? Empl_UsuarioCreacion { get; set; }
        public DateTime? Empl_FechaCreacion { get; set; }
        public int? Empl_UsuarioModificacion { get; set; }
        public DateTime? Empl_FechaModificacion { get; set; }
        public bool? Empl_Estado { get; set; }

        public virtual tbCargos Carg { get; set; }
        public virtual tbUsuarios Empl_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Empl_UsuarioModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles Esta { get; set; }
        public virtual tbMunicipios Muni_CodigoNavigation { get; set; }
        public virtual tbSucursales Sucu { get; set; }
        public virtual ICollection<tbFactura> tbFactura { get; set; }
        [NotMapped]
        public string FechaModificacion { get; set; }

        [NotMapped]
        public string FechaCreacion { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }
}