// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbFacturaDetalles
    {
        public int FaxD_Id { get; set; }
        public bool? FaxD_Dif { get; set; }
        public int? Prod_Id { get; set; }
        public int? FaxD_Cantidad { get; set; }
        public int? Fact_Id { get; set; }

        public virtual tbFactura Fact { get; set; }
    }
}