// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbFacturaCompraDetalle
    {
        public int FaCD_Id { get; set; }
        public int? FaCE_Id { get; set; }
        public bool? FaCD_Dif { get; set; }
        public int? Prod_Id { get; set; }
        [NotMapped]
        public string Producto { get; set; }
        [NotMapped]
        public string Cantidad { get; set; }
        [NotMapped]
        public string Categoria { get; set; }
        [NotMapped]
        public string Precio_Venta { get; set; }
        [NotMapped]
        public string PrecioVenta { get; set; }
        [NotMapped]
        public string PrecioMayorista { get; set; }
        [NotMapped]
        public string Total { get; set; }

        [NotMapped]
        public string mepa_Id { get; set; }

        public int? FaCD_Cantidad { get; set; }
        [NotMapped]
        public string NombreProveedor { get; set; }
        [NotMapped]
        public string mepa_Metodo { get; set; }
        [NotMapped]
        public string faCE_fechafinalizacion { get; set; }
        public virtual tbFacturaCompraEncabezado FaCE { get; set; }
    }
}