// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbFacturaDetalles
    {
        public int FaxD_Id { get; set; }
        public string? FaxD_Dif { get; set; }
        public int? Prod_Id { get; set; }
        public int? FaxD_Cantidad { get; set; }
        public int? total { get; set; }
        public int? Fact_Id { get; set; }
        [NotMapped]
        public string? Prod_Nombre { get; set; }
        [NotMapped]
        public string? TotalFinal { get; set; }

        [NotMapped]
        public string? Genero { get; set; }

        [NotMapped]
        public string? TotalCompras { get; set; }

        [NotMapped]
        public string? Producto { get; set; }

        [NotMapped]
        public string? NombreProducto { get; set; }



        [NotMapped]
        public string? TotalVendido { get; set; }



        [NotMapped]
        public string? Cantidad { get; set; }

        [NotMapped]
        public string? TipoProducto { get; set; }


        [NotMapped]
        public string? PrecioVenta { get; set; }

        [NotMapped]
        public string? Mes { get; set; }

        [NotMapped]
        public string? TotalVentas { get; set; }



        [NotMapped]
        public string? VentasJoyas { get; set; }
        [NotMapped]
        public string? VentasMaquillaje { get; set; }



        public virtual tbFactura Fact { get; set; }
    }
}