// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbFacturaCompraEncabezado
    {
        public tbFacturaCompraEncabezado()
        {
            tbFacturaCompraDetalle = new HashSet<tbFacturaCompraDetalle>();
        }

        public int FaCE_Id { get; set; }
        public int? Prov_Id { get; set; }
        public int? Mepa_Id { get; set; }
        public DateTime? FaCE_fechafinalizacion { get; set; }
        public int? FeCE_UsuarioCreacion { get; set; }
        public DateTime? FaCE_FechaCreacion { get; set; }
        public int? FaCE_UsuarioModificacion { get; set; }
        public DateTime? FaCE_FechaModificacion { get; set; }

        public virtual tbMetodosPago Mepa { get; set; }
        public virtual tbProveedores Prov { get; set; }
        public virtual ICollection<tbFacturaCompraDetalle> tbFacturaCompraDetalle { get; set; }
    }
}