// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbJoyas
    {
        [NotMapped]
        public int Joya_Stock { get; set; }
        [NotMapped]
        public string Mate_Material { get; set; }
        [NotMapped]
        public string Prov_Proveedor { get; set; }
        [NotMapped]
        public string Cate_Categoria { get; set; }
        public int Joya_Id { get; set; }
        public string Joya_Nombre { get; set; }
        public decimal Joya_PrecioCompra { get; set; }
        public decimal Joya_PrecioVenta { get; set; }
        public decimal Joya_PrecioMayor { get; set; }
        public string Joya_Imagen { get; set; }
        public int Prov_Id { get; set; }
        public int Mate_Id { get; set; }
        public int Cate_Id { get; set; }
        public int? Joya_UsuarioCreacion { get; set; }
        public DateTime? Joya_FechaCreacion { get; set; }
        public int? Joya_UsuarioModificacion { get; set; }
        public DateTime? Joya_FechaModificacion { get; set; }
        public bool? Joya_Estado { get; set; }
        [NotMapped]
        public string FechaModificacion { get; set; }

        [NotMapped]
        public string FechaCreacion { get; set; }
        public virtual tbCategorias Cate { get; set; }
        public virtual tbUsuarios Joya_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Joya_UsuarioModificacionNavigation { get; set; }
        public virtual tbMateriales Mate { get; set; }
        public virtual tbProveedores Prov { get; set; }

        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }
}