// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbMarcas
    {
        public tbMarcas()
        {
            tbMaquillajes = new HashSet<tbMaquillajes>();
        }

        public int Marc_Id { get; set; }
        public string Marc_Marca { get; set; }
        public int? Marc_UsuarioCreacion { get; set; }
        public DateTime? Marc_FechaCreacion { get; set; }
        public int? Marc_UsuarioModificacion { get; set; }
        public DateTime? Marc_FechaModificacion { get; set; }
        public bool? Marc_Estado { get; set; }

        public virtual tbUsuarios Marc_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Marc_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbMaquillajes> tbMaquillajes { get; set; }
        [NotMapped]
        public string UsuarioCreacion { get; set; }

        [NotMapped]
        public string UsuarioModificacion { get; set; }
    }
}