// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbPreciosBitacora
    {
        public int Prec_Id { get; set; }
        public string Prec_Nombre { get; set; }
        public decimal? Prec_PrecioCompra { get; set; }
        public decimal? Prec_PrecioVenta { get; set; }
        public decimal? Prec_PrecioMayor { get; set; }
    }
}