// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbProductosPorSucursalesEncabezados
    {
        public int Pren_Id { get; set; }
        public int? Sucu_Id { get; set; }
        public int? Pren_UsuarioCreacion { get; set; }
        public DateTime? Pren_FechaCreacion { get; set; }
        public int? Pren_UsuarioModificacion { get; set; }
        public DateTime? Pren_FechaModificacion { get; set; }
        public bool? Pren_Finalizado { get; set; }
        public bool? Pren_Estado { get; set; }
    }
}