// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbProductosPorSucurales
    {
        public int Prxs_Id { get; set; }
        public bool? Prxs_Dif { get; set; }
        public int? Prod_Id { get; set; }
        public int? Prsx_Stock { get; set; }
        public int? Sucu_Id { get; set; }
    }
}