// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbProductosPorSucurales
    {
        [NotMapped]
        public string? Prod_Nombre { get; set; }
        [NotMapped]
        public string? SucuEnviado { get; set; }
        [NotMapped]
        public string id { get; set; }
        [NotMapped]
        public string nombre { get; set; }
        [NotMapped]
        public string stock { get; set; }
        [NotMapped]
        public string compra { get; set; }
        [NotMapped]
        public string venta { get; set; }

        [NotMapped]
        public string mayor { get; set; }

        [NotMapped]
        public string tipo { get; set; }
        public int Prxs_Id { get; set; }

        public int Pren_Id { get; set; }
        public string? Prxs_Dif { get; set; }
        public int? Prod_Id { get; set; }
        public int? Prsx_Stock { get; set; }
        public int? Sucu_Id { get; set; }
    }
}