// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbCategorias
    {
        public tbCategorias()
        {
            tbJoyas = new HashSet<tbJoyas>();
        }

        public int Cate_Id { get; set; }
        public string Cate_Categoria { get; set; }
        public int? Cate_UsuarioCreacion { get; set; }
        public DateTime? Cate_FechaCreacion { get; set; }
        public int? Cate_UsuarioModificacion { get; set; }
        public DateTime? Cate_FechaModificacion { get; set; }
        public bool? Cate_Estado { get; set; }

        public virtual tbUsuarios Cate_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Cate_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbJoyas> tbJoyas { get; set; }
    }
}