// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbClientes
    {
        public tbClientes()
        {
            tbFactura = new HashSet<tbFactura>();
        }

        public int Clie_Id { get; set; }
        public string Clie_Nombre { get; set; }
        public string Clie_Apellido { get; set; }
        public DateTime Clie_FechaNac { get; set; }
        public string Clie_Sexo { get; set; }
        public string Muni_Codigo { get; set; }
        public int Esta_Id { get; set; }
        public int? Clie_UsuarioCreacion { get; set; }
        public DateTime? Clie_FechaCreacion { get; set; }
        public int? Clie_UsuarioModificacion { get; set; }
        public DateTime? Clie_FechaModificacion { get; set; }
        public bool? Clie_Estado { get; set; }

        public virtual tbUsuarios Clie_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Clie_UsuarioModificacionNavigation { get; set; }
        public virtual tbEstadosCiviles Esta { get; set; }
        public virtual tbMunicipios Muni_CodigoNavigation { get; set; }
        public virtual ICollection<tbFactura> tbFactura { get; set; }
    }
}