// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbImpuestos
    {
        public tbImpuestos()
        {
            tbFactura = new HashSet<tbFactura>();
        }

        public int Impu_Id { get; set; }
        public decimal? Impu_Impuesto { get; set; }
        public int? Impu_UsuarioCreacion { get; set; }
        public DateTime? Impu_FechaCreacion { get; set; }
        public int? Impu_UsuarioModificacion { get; set; }
        public DateTime? Impu_FechaModificacion { get; set; }
        public bool? Impu_Estado { get; set; }

        public virtual tbUsuarios Impu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Impu_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbFactura> tbFactura { get; set; }
    }
}