// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbMaquillajes
    {
        public int Maqu_Id { get; set; }
        public string Maqu_Nombre { get; set; }
        public decimal Maqu_PrecioCompra { get; set; }
        public decimal Maqu_PrecioVenta { get; set; }
        public decimal Maqu_PrecioMayor { get; set; }
        public string Maqu_Imagen { get; set; }
        public int Prov_Id { get; set; }
        public int Marc_Id { get; set; }
        public int? Maqu_UsuarioCreacion { get; set; }
        public DateTime? Maqu_FechaCreacion { get; set; }
        public int? Maqu_UsuarioModificacion { get; set; }
        public DateTime? Maqu_FechaModificacion { get; set; }
        public bool? Maqu_Estado { get; set; }

        public virtual tbUsuarios Maqu_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Maqu_UsuarioModificacionNavigation { get; set; }
        public virtual tbMarcas Marc { get; set; }
        public virtual tbProveedores Prov { get; set; }
    }
}