// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbMateriales
    {
        public tbMateriales()
        {
            tbJoyas = new HashSet<tbJoyas>();
        }

        public int Mate_Id { get; set; }
        public string Mate_Material { get; set; }
        public int? Mate_UsuarioCreacion { get; set; }
        public DateTime? Mate_FechaCreacion { get; set; }
        public int? Mate_UsuarioModificacion { get; set; }
        public DateTime? Mate_FechaModificacion { get; set; }
        public bool? Mate_Estado { get; set; }

        public virtual tbUsuarios Mate_UsuarioCreacionNavigation { get; set; }
        public virtual tbUsuarios Mate_UsuarioModificacionNavigation { get; set; }
        public virtual ICollection<tbJoyas> tbJoyas { get; set; }
    }
}