// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace SistemaEsmeralda.Entities.Entities
{
    public partial class tbPantallasXRoles
    {
        public int Paxr_Id { get; set; }
        public int? Role_Id { get; set; }
        public int? Pant_Id { get; set; }

        public virtual tbPantallas Pant { get; set; }
        public virtual tbRoles Role { get; set; }
    }
}