export class FacturaCompraEncabezado{
    faCE_Id ?: String;
    prov_Id !: Number;
    mepa_Id !: Number;
    faCE_fechafinalizacion !: String;
    feCE_UsuarioCreacion !: Number;
    faCE_FechaCreacion !: String;
    faCE_UsuarioModificacion !: Number;
    faCE_FechaModificacion !: String;
    prov_Proveedor !: String;
    mepa_Metodo !: String;
    usuarioCreacion !: String;
    usuarioModificacion !: String;
    precioVenta ?: String;
    precioMayor ?: String;
    precioCompra ?: String;
    prod_Producto ?: String;
    nombreProducto ?: String;
}
export class CrearFacturaCompraEncabezado{
    mepa_Id !: Number;
    prov_Id !: Number;
    faCE_Id ?: String;
    faCD_Dif ?: String;
    nombreProducto ?: String;
    prod_Id !: Number;
    faCD_Cantidad !: String;
    precioCompra ?: String;
    precioMayor ?: String;
}
export class FacturaCompraDetalle{
    faCD_Id !: Number;
    faCE_Id !: Number;
    faCD_Dif !: String;
    prod_Id !: Number;
    nombreProducto !: String;
    faCD_Cantidad !: String;
    prod_Producto ?: String;
    prod_Nombre ?: String;
    precioVenta ?: String;
    precioMayor ?: String;
    precioCompra ?: String;
}